### ISSUE TITLE
Links in dialogs don't look like links

### ISSUE THREAD

**Issue by mlocati** [concrete5/bedrock#377]
In `assets/cms/scss/jquery-ui/_theme.scss` we have these lines in bedrock 1.5.x:

```css
.ui-widget-content a {
  color: #333;
}
```

and in bedrock 1.6.x:
```css
.ui-widget-content a {
  color: var(--bs-body-color);
}
```

With these styles, links don't look like links.

For example, the following HTML

```html
<p>This is a text, and <a href="#">this is a link</a>.</p>
```

is rendered like this in ConcreteCMS 9.3 and 9.4:

![Image](https://github.com/user-attachments/assets/d7fce764-164d-4863-a5b2-07c4085ae5c3)
